[package]
name = "sparkypi"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.14.1"
clap = { version = "4.2.1", features = ["derive"] }
